[project]
name = 'web3-workshop'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.basic-stacking-platform]
path = 'contracts/basic-stacking-platform.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nft-expense-tracker-app]
path = 'contracts/basic-stacking-platform.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
